---
name: learn-bosh
director_uuid: ${director_uuid}

releases:
- name: learn-bosh-release-name
  version: latest

networks:
- name: ${network_name}
  subnets:
  - range: ${network_range}
    gateway: ${network_gateway}

resource_pools:
- name: ${resource_name}
  stemcell:
    name: ${stemcell_name}
    version: latest
  network: ${network_name}
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: app
  templates:
  - name: app
  instances: 1
  resource_pool: ${resource_name}
  networks:
  - name: ${network_name}
  properties: {}
